import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import Script from 'next/script'

import NavBar from '@/components/navbar/NavBar'

import Providers from '@/providers/Providers'
import { getCurrentUser } from '@/actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

// https://github.com/vercel/next.js/pull/53525

export const metadata: Metadata = {
  title: {
    default: 'Link Orchard',
    template: '%s | Link Orchard'
  },
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
  auth: React.ReactNode
  admin: React.ReactNode
}

export default async function RootLayout({ children, auth }: RootLayoutProps) {
  const nonce = headers().get('x-nonce')

  const currentUser = await getCurrentUser()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers attribute="class" enableSystem>
          <NavBar currentUser={currentUser} />
          <main className="h-screen flex justify-center ">
            {children}
            {auth}
          </main>
        </Providers>
      </body>
      <Script strategy="afterInteractive" nonce={nonce || ''} />
    </html>
  )
}
