import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import NavBar from '@/components/navbar/NavBar'

import Providers from '@/providers/Providers'

const inter = Inter({ subsets: ['latin'] })

// https://github.com/vercel/next.js/pull/53525

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  auth
}: // auth
{
  children: React.ReactNode
  auth: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers attribute="class" enableSystem>
          <NavBar home />
          <section className="h-screen flex justify-center pt-16 ">
            {children}
            {auth}
          </section>
        </Providers>
      </body>
    </html>
  )
}
